### ISSUE TITLE
VBox: alignment options don't play well with RTL

### ISSUE THREAD

**Issue by alisey** [wix/wix-ui#393]
This is how horizontal alignment is currently defined in the VBox:

```js
export type Alignment = 'left' | 'center' | 'right';
```

And here's the corresponding CSS:

```css
.root:horizontalAlignment(left) {
    align-items: flex-start;
}

.root:horizontalAlignment(center) {
    align-items: center;
}

.root:horizontalAlignment(right) {
    align-items: flex-end;
}
```

The problem is that the meaning of `flex-start` and `flex-end` depends on the direction mode: https://jsfiddle.net/c13c4ra2/

So our `left` can become right, and our `right` can become left, which is confusing.

I suggest that we simply rename `left` and `right` to `start` and `end`.
