### ISSUE TITLE
Theming class - what is it good for?

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#888]
## Current status
Currently we have the first pioneer component `button-next` in `wix-ui-core`, which is using the "new" theming methodology.
Specifically, it's css stylesheet scopes every rule with a `backoffice_root` class.
> button-next.st.css
```css
:import {
  -st-from: '../theme.st.css';
  -st-default: BackofficeTheme;
}

BackofficeTheme .button {
  box-sizing: border-box;
  text-align: center;
  ...
}
```

So in order to use the button, you need to do : 
>Consumer.js
```js
import {backofficeTheme} from 'wix-ui-core/src/themes/backoffice';
import buttonNextStyle from 'wix-ui-core/src/themes/backoffice/button-next';
import {ButtonNext} from 'wix-ui-core';

export default () => (
  <div className={backofficeTheme}>
    <ButtonNext className={classNames(
        buttonNextStyle.button,
        buttonNextStyle.premium
      )}
   />
  </div>
)
```

## There is no use-case for the `backofficeTheme` class
I think we can remove the `backofficeTheme` class from the `backoffice/button-next.st.css` .
- the `buttonNextStyle.button` and `buttonNextStyle.premium` are already backoffice theme classes.
- If we were to switch the `backofficeTheme` to `adiTheme` then it won't work. We'll have no styling at all.

## For theming to really work
For theming to really work, in our case, the `premium` class should be defined in the component itself (button-next.st.css) with empty rules, and then both `backoffice` and `adi` themes could extend it.

## Coupling Design-Systems
Now I 'm not sure this is a real use-case at all.
And do we want our design systems to be so much coupled?

## Finally
@shlomitc @nadavov @JoMarton 
Can we drop the `backofficeTheme` class?

**Comment by hepiyellow** [comment]
As discussed with @nadavov ,
theming could be useful in case of composites.

## Composite Use-case
So if we have a composite component that uses, say, Button component.

**Comment by mykas** [comment]
I agree with @hepiyellow regarding dropping it as I don't understand whats the point of having additional generated class name when classes in themes folder are generated random in the end anyway.

For example current situation is:
`import buttonNextStyle from 'wix-ui-core/src/themes/backoffice/button-next';`

which is:
```css 
BackofficeTheme .button {
  box-sizing: border-box;
  text-align: center;
  border: 1px solid;

  -st-mixin: sizeMedium, weightNormal;

  outline: none;
  transition: all 100ms linear;

  height: 36px;
  border-radius: 18px;
  padding: 0 23px;

  background-color: value(B10);
  border-color: value(B10);
  color: value(D80);
}
```

the ouput will be:
```css
<div class="BackofficeTheme324690182--root">
    <button class="buttonnext1637977129--root Focusable2109143506--root button3214162869--button">Button</buttton>
</div>
```

as we see we have generated classes like ` button3214162869--button` which are unique itself anyway.  No other stylable stylesheet will have such class generated. 

So my question is: whats the point of backofficeTheme scope?

**Comment by mykas** [comment]
Regarding `For theming to really work` part. I am not sure if we should add `premium` to the root component. What if backoffice will drop `premium` styles? Why do you think we should add it there, anyway?

**Comment by hepiyellow** [comment]
@mykas 
Say there is a composite `<Dialog/> with `cancel` and `confirm` buttons.
then you might want to reuse that `<Dialog/>` in both Backoffice and ADI.

If we would have say Button.primary and Button.secondary classes defined in the Button component stylsheet (or any other common stylesheet), then you could reuse the `<Dialog/>` component from both Backoffice and ADI with *css only*.

## Theming Technique 1

The Dialog would have:
> Dialog.js (wix-ui-core)
```js
import buttonStyle from '../button/button.st.css'; // core stylesheet

export default => (
  <div>
    <Button class={buttonStyle.primary}>Confirm</Button>
    <Button class={buttonStyle.secondary}>Cancel</Button>
  </div
)
```

And Backoffice and ADI can simply extend the `Button.primary` and `Button.secondary` classes.
>`Backoffice.st.css`
```css
:import {
  -st-from: '../../../components/dialog/dialog.st.css';
  -st-default: Dialog;
}
:import {
  -st-from: '../../../components/button/button.st.css';
  -st-default: Button;
  -st-named: primary, secondary;
}

Button.primary {
  color: black;
}

Button.secondary {
  color: grey;
}

```
 and use like this:
> backoffice consumer
```js
import backofficeTheme from '../some/path/backoffice.st.css';

export default => (
  <Dialog />
)
```
It should be enough to import the backoffice theme. And it will affect all `Button`s.
- With this technique thought you can't mix Backoffice and ADI in the same page. Which is reasonable.

## Theming Technique 2
Technique 1 is not so confronting to the idea of wix-ui-core reusable components.
The `<Dialog/>` should have element selectors (`confirmButton` and `cancelButton`) instead of `primary` and `secondary` styles:
> Dialog.js (wix-ui-core)
```js
import buttonStyle from '../button/button.st.css'; // core stylesheet
import dialogStyle from './style.st.css';

export default => (
  <div>
    <Button class={dialogStyle.confirmButton}>Confirm</Button>
    <Button class={dialogStyle.cancelButton}>Cancel</Button>
  </div
)
```

With this technique there is not real way to share between Backoffice & ADI, that confirm button should be `primary` and `cancel button should be `secondary`. Unless you add another JS layer.

So a consumer would have to do:
> some-comp-rendering-dialog.js
```js
import backofficeTheme from '../some/path/backoffice.st.css';

export default => (
  <Dialog />
)
```

>`backoffice-theme.st.css`
```css
:import {
  -st-from: '../../../components/dialog/dialog.st.css';
  -st-default: Dialog;
  -st-named: confirmButton, cancelButton;
}
:import {
  -st-from: '../../../components/button/button.st.css';
  -st-default: Button;
  -st-named: primary, secondary;
}

.buttonPrimary {
  color: black;
}

.buttonSecondary {
  color: grey;
}

Button.primary {
 -st-mixin: .buttonPrimary;
}

Button.secondary {
 -st-mixin: .buttonSecondary;
}

Dialog::confirmButton {
  -st-mixin: .buttonPrimary;
}

Dialog::cancelButton {
  -st-mixin: .buttonSecondary;
}
```

> NOTE: using `-st-mixin` produces redundant duplicate css rules. But Stylable doesn't yet support `-st-extends` for complex selectors.

**Comment by mykas** [comment]
Thanks, 1st Technique make sense now.

**Comment by JoMarton** [comment]
I am all for dropping the scoping class for the sake of simplicity.

I thought it was put there to begin with for some reason, so whatever you guys decide I'm good with

**Comment by shahata** [comment]
Not all components will have class names for variants such as premium button etc.

The theme class should appear one time in the root of the app to enforce the default variant of that theme on all components in the tree.

**Comment by hepiyellow** [comment]
## One Theme per page VS. multiple Themes per page

**Let's relate only to style API that is in the core component.**

### One Theme per page
 If we assume one theme per page, we can have the theme stylesheet :
#### Example
> backoffice-core-theme.st.css
```css
:import {
  -st-from: 'wix-ui-core/button.st.css';
  -st-default: Button;
}

Button {
  border: 1px solid;
}
```
A consumer App would look like this:
> App.js
```js
import 'wix-ui-backoffice/backofficeCoreTheme.st.css'

export default => (
  <div>
    <Button>Click me</Button>
  </div
)
```

#### Analysis

- Notice we use the `Button` class which is the root class of the `<Button/>` component in the core.
- We can not have 2 Themes in a page this way, since the "later-loaded" theme will override the first one.
- There is no actual `backofficeCoreTheme` class.
- The consumer App simply loads the backoffice theme stylsheet.
- This works only since Stylable removed the [auto `root` scoping](https://github.com/wix/stylable/issues/217).

### Multiple Themes per page

#### Example
> backoffice-core-theme.st.css
```css
:import {
  -st-from: 'wix-ui-core/button.st.css';
  -st-default: Button;
}

.root Button {
  border: 1px solid;
}
```
> adi-core-theme.st.css
```css
:import {
  -st-from: 'wix-ui-core/button.st.css';
  -st-default: Button;
}

.root Button {
  border: 5px solid;
}
```

A consumer App would look like this:
> App.js
```js
import backofficeTheme from 'wix-ui-backoffice/backofficeCoreTheme.st.css'
import adiTheme from 'wix-ui-adi/adiCoreTheme.st.css'

export default => (
  <div>
    <div className={backofficeTheme.root}>
      <Button>Click me</Button>
    </div>
    <div className={adiTheme.root}>
      <Button>Click me</Button>
    </div>
  </div
)
```

#### Analysis

- Notice we use the `.root Button` selector.
- 2 Themes in a page works (Just you can't nest the themes within each other)
- There are 2 theme classes `backofficeCoreTheme.root` and `adiCoreTheme.root`.
- The consumer App need only to put one class per themed section.

## Conclusion & ActionItems
Only thing to decide now is:

**Do we want to support multiple themes in one page?**

In our next chapter, we will look at extending the core's style API.

**Comment by hepiyellow** [comment]
## Chapter 2 - extending a common style API (core api in this case)

### One Theme per page.

> backoffice-extending-theme.st.css
```css
:import {
  -st-from: 'wix-ui-core/button.st.css';
  -st-default: Button;
}

Button.skinPremium( {
  background-color: purple;
}
```

### Multiple Themes per page.

> backoffice-extending-theme.st.css
```css
:import {
  -st-from: 'wix-ui-core/button.st.css';
  -st-default: Button;
}

Button.skinPremium( {
  background-color: purple;
}
```

## Analysis

- Hmm. that's interesting in both one/multiple theme per page, the extending stylesheet looks the same.
- That's because `skinPremium` class is unique to the `backoffice-extending-theme` stylesheet.

## Consumer of multiple Themes per page
```js
import backofficeCoreTheme from 'wix-ui-backoffice/backofficeCoreTheme.st.css'
import adiCoreTheme from 'wix-ui-adi/adiCoreTheme.st.css'

import backofficeExtendingTheme from 'wix-ui-backoffice/backofficeExtendingTheme.st.css'

export default => (
  <div>
    <div className={backofficeCoreTheme.root}>
      <Button className={backofficeExtendingTheme.skinPremium}>Click me</Button>
    </div>
    <div className={adiCoreTheme.root}>
      <Button>Click me</Button>
    </div>
  </div
)
```

To be continued....
